### ISSUE TITLE
 file COPY cannot find

### ISSUE THREAD

**Issue by chluck2008** [iwatake2222/detection_topview#1]
i use nvidia nano  
CMake Error at inference_helper/third_party/cmakes/tflite.cmake:29 (file):
  file COPY cannot find
  "/home/nvidia/self-driving-ish_computer_vision_system/inference_helper/third_party/cmakes/../tensorflow_prebuilt/aarch64/libtensorflowlite.so".
Call Stack (most recent call first):
  inference_helper/inference_helper/CMakeLists.txt:78 (include)

**Comment by iwatake2222** [comment]
You need all the steps described here:  https://github.com/iwatake2222/self-driving-ish_computer_vision_system#common
This ("You don't need this step if you use TensorRT")  description is wrong. I'll fix it.

**Comment by chluck2008** [comment]
In file included from /home/nvidia/self-driving-ish_computer_vision_system/inference_helper/inference_helper/inference_helper_tensorrt.cpp:32:0:
/home/nvidia/self-driving-ish_computer_vision_system/inference_helper/inference_helper/tensorrt/common.h: In function ‘uint32_t samplesCommon::getElementSize(nvinfer1::DataType)’:
/home/nvidia/self-driving-ish_computer_vision_system/inference_helper/inference_helper/tensorrt/common.h:650:30: error: ‘kBOOL’ is not a member of ‘nvinfer1::DataType’
     case nvinfer1::DataType::kBOOL:

**Comment by iwatake2222** [comment]
It looks you are using old version of JetPack and TensorRT

**Comment by chluck2008** [comment]
最新的版本是4.4但CUDA是10.2,不是10.0
The latest version is 4.4, but CUDA is 10.2, not 10.0

**Comment by chluck2008** [comment]
请问tensorrt的版本是多少

**Comment by iwatake2222** [comment]
As written in README (https://github.com/iwatake2222/self-driving-ish_computer_vision_system#computer) , you need to use JetPack 4.6 which indeludes TensorRT8

**Comment by chluck2008** [comment]
Cuda compilation tools, release 10.2, V10.2.89
     tensorrt                                      7.1.3.0-1+cuda10.2 

[  5%] Building CXX object inference_helper/CMakeFiles/InferenceHelper.dir/inference_helper_tensorrt.cpp.o
/home/nvidia/self-driving-ish_computer_vision_system/inference_helper/inference_helper/inference_helper_tensorrt.cpp: In member function ‘virtual int32_t InferenceHelperTensorRt::Initialize(const string&, std::vector<InputTensorInfo>&, std::vector<OutputTensorInfo>&)’:
/home/nvidia/self-driving-ish_computer_vision_system/inference_helper/inference_helper/inference_helper_tensorrt.cpp:177:69: error: ‘class nvinfer1::IBuilder’ has no member named ‘buildSerializedNetwork’
         auto plan = std::unique_ptr<nvinfer1::IHostMemory>(builder->buildSerializedNetwork(*network, *config));
                                                                     ^~~~~~~~~~~~~~~~~~~~~~
In file included from /home/nvidia/self-driving-ish_computer_vision_system/inference_helper/inference_helper/inference_helper_tensorrt.cpp:32:0:
/home/nvidia/self-driving-ish_computer_vision_system/inference_helper/inference_helper/tensorrt/common.h: In instantiation of ‘void samplesCommon::InferDeleter::operator()(T*) const [with T = nvinfer1::IBuilder]’:
/usr/include/c++/7/bits/unique_ptr.h:263:17:   required from ‘std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = nvinfer1::IBuilder; _Dp = samplesCommon::InferDeleter]’
/home/nvidia/self-driving-ish_computer_vision_system/inference_helper/inference_helper/tensorrt/common.h:962:116:   required from here
/home/nvidia/self-driving-ish_computer_vision_system/inference_helper/inference_helper/tensorrt/common.h:387:9: error: ‘virtual nvinfer1::IBuilder::~IBuilder()’ is protected within this context
         delete obj;
         ^~~~~~
In file included from /home/nvidia/self-driving-ish_computer_vision_system/inference_helper/inference_helper/inference_helper_tensorrt.cpp:30:0:
/usr/include/aarch64-linux-gnu/NvInfer.h:7098:13: note: declared protected here
     virtual ~IBuilder()
             ^
In file included from /usr/include/c++/7/memory:80:0,
                 from /home/nvidia/self-driving-ish_computer_vision_system/inference_helper/inference_helper/inference_helper_tensorrt.cpp:26:
/usr/include/c++/7/bits/unique_ptr.h: In instantiation of ‘void std::default_delete<_Tp>::operator()(_Tp*) const [with _Tp = nvinfer1::IRuntime]’:
/usr/include/c++/7/bits/unique_ptr.h:263:17:   required from ‘std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = nvinfer1::IRuntime; _Dp = std::default_delete<nvinfer1::IRuntime>]’
/home/nvidia/self-driving-ish_computer_vision_system/inference_helper/inference_helper/inference_helper_tensorrt.h:35:7:   required from here
/usr/include/c++/7/bits/unique_ptr.h:78:2: error: ‘virtual nvinfer1::IRuntime::~IRuntime()’ is protected within this context
  delete __ptr;
  ^~~~~~
