### ISSUE TITLE
how build tensorflow-lite

### ISSUE THREAD

**Issue by cqray1990** [iwatake2222/detection_topview#12]
## Environment (Hardware)
- Hardware: Device, CPU, GPU, etc.
- Software: OS, Compiler, etc.
(Please include version information)

## Issue Details
A clear and concise description of what the issue is.

## How to Reproduce
Steps to reproduce the behavior. Please include your cmake command.

## Error Log
```
error log
```

**Comment by iwatake2222** [comment]
https://www.tensorflow.org/lite/guide/build_cmake
