### ISSUE TITLE
make report error

### ISSUE THREAD

**Issue by hydradrianfyh** [iwatake2222/detection_topview#13]
## Environment 
ubuntu 18.04
NV Geforce MX330
cuda version 11.5

(Please include version information)

## Issue Details
report error “NvInfer.h: No such file or directory”
![image](https://user-images.githubusercontent.com/65054596/169211352-fe798721-8943-4eba-9f55-fce08a32d2aa.jpeg)

**Comment by iwatake2222** [comment]
Probably, you use older TensorRT
