### ISSUE TITLE
Compatibility with new jetson Orin

### ISSUE THREAD

**Issue by jcgomez11** [iwatake2222/detection_topview#15]
Is it possible to use this project with the new Jetson Orin? 
It is written on the website that it will use jetpack 5.0 with CUDA 11.4, in that case it will need to use Tensorrt 8.2 instead of the 8.0 version, would that might be a problem?

**Comment by iwatake2222** [comment]
I'm not sure because I don't have Jetson Orin, but it may work.

**Comment by iwatake2222** [comment]
This issue was closed because it has been inactive.
