### ISSUE TITLE
How to use my camera to measure distance.

### ISSUE THREAD

**Issue by bijou321** [iwatake2222/detection_topview#18]
I want to know the accuracy of distance result.
when i use my camera with the following parameter.
1920*1080 ,Horizontal fov  degree：113.
The height of the camera to the ground is 0.9 m.
I test the distance, The farther the distance, the more inaccurate.

can you tell me if the result is normal?
if not,how can i fix it?

**Comment by iwatake2222** [comment]
> The farther the distance, the more inaccurate.

Yes, it's normal result.

If your camera doesn't have any lens distortion, the height is exactly 0.900m and pitch/yaw/roll is 0.000 degree, you'll get accurate result. However, it's almost impossible...
