### ISSUE TITLE
Is needed to build OpenCV 4.X from source with CUDA and cuDNN?

### ISSUE THREAD

**Issue by Francisco-Aguilera-xd** [iwatake2222/detection_topview#20]
Hello!

This project requires OpenCV 4.X. Can I use the direct download (windows in my case) from OpenCV page, or I have to build the library from source and enable CUDA and cuDNN (like what is done in this [video] (https://www.youtube.com/watch?v=-GY2gT2umpk)

**Comment by iwatake2222** [comment]
You can use the downloaded OpenCV. You don't need to build OpenCV.
