### ISSUE TITLE
This is AWESOME - Want an OAK-D-Lite (or any others)?

### ISSUE THREAD

**Issue by Luxonis-Brandon** [iwatake2222/detection_topview#4]
Hi @iwatake2222 ,

We'd love to send you and OAK-D-Lite (and/or any other models) to play with.  

![20210914152158_7V0A1957](https://user-images.githubusercontent.com/32992551/133284613-1242e064-0bd3-4e1d-845b-c78f7c7b5b10.JPG)

It has 13MP integrated color camera with 4k encoder built in and a stereo pair of OV7251 for being able to do disparity depth.  And you can do neural-depth approaches onboard too.  The device has about 1.4TOPS of neural compute capability built-in.  And 4 TOPS total and can handle about 500 million pixels/second while running AI+depth+CV functions in parallel.

Some examples of neural depth running below:
https://github.com/luxonis/depthai-experiments/blob/a906af308f3dfcee729a6351c0a7ea2f7437e693/gen2-depth-mbnv2/README.md
https://github.com/luxonis/depthai-experiments/blob/f967cc4298a01646133b5f952dc2c402918d3a8a/gen2-fast-depth/README.md

And the algorithmic disparity depth (Census Transform based) is here:
https://youtu.be/IobXWORCYJs

Feel free to shoot me an email at brandon at luxonis dot com and we'll get one your way.  We think you'll love it.  :-). (And at the very least, it'll look cool on your desk.)

-Brandon
Luxonis \\ OpenCV Team

**Comment by iwatake2222** [comment]
Thank you for reaching out to me. I'm happy to hear that you like my project. I'm very interested in OAK-D, but I couldn't get it because it was sold out as soon as it was listed on shop. I'm excited that you are releasing new one(OAK-D-Lte). I'd love to create something with it.
I'll send email to you. ( take.iwiw2222 at gmail dot com)

Thank you!

**Comment by Luxonis-Brandon** [comment]
Awesome, thanks!  Looking forward to it!
