### ISSUE TITLE
error installation on Nvidia Xavier.

### ISSUE THREAD

**Issue by khaledgabr77** [iwatake2222/detection_topview#5]
## Environment (Hardware)
- Hardware: Nvidia Xavier, JetPack 4.6.
- Software: Ubuntu 18.04 LTS.

## Issue Details
When trying to download the source last step `tensorflow/lite/tools/make/download_dependencies.sh` it show me this error:
downloading https://gitlab.com/libeigen/eigen/-/archive/12e8d57108c50d8a63605c6eb0144c838c128337/eigen-12e8d57108c50d8a63605c6eb0144c838c128337.tar.gz
tensorflow/lite/tools/make/download_dependencies.sh: line 90: curl: command not found

## Error Log
```
downloading https://gitlab.com/libeigen/eigen/-/archive/12e8d57108c50d8a63605c6eb0144c838c128337/eigen-12e8d57108c50d8a63605c6eb0144c838c128337.tar.gz
tensorflow/lite/tools/make/download_dependencies.sh: line 90: curl: command not found
```

**Comment by iwatake2222** [comment]
Please install curl. The command is like `sudo apt install curl`

**Comment by khaledgabr77** [comment]
Thanks, it compied fine. 
but when try to launch `./main` i got some errors. 
```
[InferenceHelper][105] Use TensorRT 
[09/15/2021-13:43:06] [I] [TRT] [MemUsageChange] Init CUDA: CPU +354, GPU +0, now: CPU 372, GPU 7926 (MiB)
[09/15/2021-13:43:06] [I] [TRT] [MemUsageChange] Init CUDA: CPU +0, GPU +0, now: CPU 372, GPU 7926 (MiB)
Could not open file /media/dp-nvidia-xavier2/XavierSSDAI/kha/self-driving-ish_computer_vision_system/build/resource//model/yolox_nano_480x640.onnx
Could not open file /media/dp-nvidia-xavier2/XavierSSDAI/kha/self-driving-ish_computer_vision_system/build/resource//model/yolox_nano_480x640.onnx
[09/15/2021-13:43:06] [E] [TRT] ModelImporter.cpp:682: Failed to parse ONNX model from file: /media/dp-nvidia-xavier2/XavierSSDAI/kha/self-driving-ish_computer_vision_system/build/resource//model/yolox_nano_480x640.onnx
[ERR: InferenceHelperTensorRt][148] Failed to parse onnx file (/media/dp-nvidia-xavier2/XavierSSDAI/kha/self-driving-ish_computer_vision_system/build/resource//model/yolox_nano_480x640.onnx)[ERR: DetectionEngine][133] Inference helper is not created
[ERR: DetectionEngine][133] Inference helper is not created
Initialization Error
```
i checked the model folder it's not contain any onnx model. i need to download right?

**Comment by iwatake2222** [comment]
Can you make sure `/media/dp-nvidia-xavier2/XavierSSDAI/kha/self-driving-ish_computer_vision_system/build/resource//model/yolox_nano_480x640.onnx` is really exist? 

Also, please open `/media/dp-nvidia-xavier2/XavierSSDAI/kha/self-driving-ish_computer_vision_system/build/resource//model/yolox_nano_480x640.onnx` on Netron (https://netron.app/) to make sure the file is not broken.

**Comment by Jiroh** [comment]
I've tested with Jetson Xavier AGX, JetPack 4.6 and works fine by the instruction on the readme. Yeah, I nee install Curl separately and bit confusing location of  models and library. Video feed from logitech C920 also works well.

**Comment by khaledgabr77** [comment]
@iwatake2222 I told you i didn't found `yolox_nano_480x640.onnx` inside the path.

**Comment by iwatake2222** [comment]
Yes, you need to download it.
Please read this part carefully. https://github.com/iwatake2222/self-driving-ish_computer_vision_system#download

After you download the model files, run cmake again to copy the files to build directory.

**Comment by khaledgabr77** [comment]
@Jiroh I have the same environment Jetson Xavier AGX, JetPack 4.6.

**Comment by khaledgabr77** [comment]
@iwatake2222  ifollowed the same [](https://github.com/iwatake2222/self-driving-ish_computer_vision_system#download ) but it doesn't appear

**Comment by khaledgabr77** [comment]
@iwatake2222  i think need to download the model from here `https://github.com/PINTO0309/PINTO_model_zoo/blob/main/132_YOLOX/download_nano_new.sh` ? and put it manual on file path.

**Comment by iwatake2222** [comment]
No. https://github.com/iwatake2222/self-driving-ish_computer_vision_system/releases/download/20210914/resource.zip
![image](https://user-images.githubusercontent.com/11009876/133416817-0a638a8d-f491-42f8-abdf-8ffdb3eccf0b.png)

**Comment by khaledgabr77** [comment]
@iwatake2222 i did this step before, i will remove the build directory and try cmake and make again.

**Comment by iwatake2222** [comment]
You might download & extract the model files into the wrong directory. If you follow the instruction, you'll see model files under `resource/model/` , Then, when you run cmake, these files are automatically copy to the build directory (the same directory as executable file)
![image](https://user-images.githubusercontent.com/11009876/133417686-a8b2e9d6-3783-48e2-ad05-e21cec3d826f.png)

**Comment by khaledgabr77** [comment]
![Screenshot from 2021-09-15 15-40-09](https://user-images.githubusercontent.com/30967695/133426873-4f658bcc-dddb-45b8-8966-5b9ed1dc5b86.png)
it's working now, the problem was it's use another path.

**Comment by cqray1990** [comment]
@khaledgabr77 
how did compile the project? i compile it as readme,but it always raise 
onsolidate compiler generated dependencies of target CommonHelper
[ 45%] Built target CommonHelper
Consolidate compiler generated dependencies of target ImageProcessor
[ 90%] Built target ImageProcessor
Consolidate compiler generated dependencies of target main
[ 95%] Linking CXX executable main

/usr/bin/ld: 找不到 -lnvinfer
/usr/bin/ld: 找不到 -lnvonnxparser
/usr/bin/ld: 找不到 -lnvinfer_plugin
/usr/bin/ld: 找不到 -lcudnn
collect2: error: ld returned 1 exit status
CMakeFiles/main.dir/build.make:228: recipe for target 'main' failed
make[2]: *** [main] Error 1
CMakeFiles/Makefile2:137: recipe for target 'CMakeFiles/main.dir/all' failed
make[1]: *** [CMakeFiles/main.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2
