### ISSUE TITLE
Ubuntu 18.04

### ISSUE THREAD

**Issue by khaledgabr77** [iwatake2222/detection_topview#6]
## Environment (Hardware)
- Hardware: Laptop.
- Software: Ubuntu 18.04 LTS.

## Issue Details
Did you tested before on Ubuntu 18.04?

## Error Log
```
```

**Comment by iwatake2222** [comment]
I didn't test on Ubuntu, but I think it should work. You may need to modify cmake settings for TensorRT.

**Comment by khaledgabr77** [comment]
Thanks @iwatake2222  it's work fine now.
