### ISSUE TITLE
inference_helper/inference_helper/inference_helper_tensorrt.cpp:30:10: fatal error: NvInfer.h: 没有那个文件或目录  #include <NvInfer.h>

### ISSUE THREAD

**Issue by cqray1990** [iwatake2222/detection_topview#7]
## Environment (Hardware)
- Hardware: Device, CPU, GPU, etc.
ubantu 18
cuda10.0

errors:
inference_helper/inference_helper/inference_helper_tensorrt.cpp:30:10: fatal error: NvInfer.h: 没有那个文件或目录
 #include <NvInfer.h>

这个tensorrt放在哪？怎么没有自动找，

**Comment by cqray1990** [comment]
if(CUDA_FOUND)

        include_directories(/usr/local/cuda-10.2/include)
        link_directories(/usr/local/cuda-10.2/lib64)

        include_directories(/home/trtproject/trt8.0lib/include)
        link_directories(/home/trtproject/trt8.0lib/lib)

        target_link_libraries(${LibraryName}
            ${CUDA_LIBRARIES}
           nvinfer
           nvonnxparser
           nvinfer_plugin
            cudnn
        )
        target_include_directories(${LibraryName} PUBLIC
            ${CUDA_INCLUDE_DIRS}
            tensorrt
        )

连接自己的trt库，编译的时候还是找不到库
/usr/bin/ld: 找不到 -lnvinfer
/usr/bin/ld: 找不到 -lnvonnxparser
/usr/bin/ld: 找不到 -lnvinfer_plugin
/usr/bin/ld: 找不到 -lcudnn

**Comment by cqray1990** [comment]
collect2: error: ld returned 1 exit status
CMakeFiles/main.dir/build.make:228: recipe for target 'main' failed
make[2]: *** [main] Error 1
CMakeFiles/Makefile2:137: recipe for target 'CMakeFiles/main.dir/all' failed
make[1]: *** [CMakeFiles/main.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Natsu-Akatsuki** [comment]
I install tensorrt using the tar way and I use include_directory() and link_directory() into the CMakeLists.txt to solve this problem, just like... include_directories($ENV{HOME}/application/TensorRT-8.0.0.3/include/)
link_directories(/usr/local/cuda/lib64/ $ENV{HOME}/application/TensorRT-8.0.0.3/lib)

**Comment by iwatake2222** [comment]
This issue was closed because it has been inactive.
